### ISSUE TITLE
Differences between the starcraft environment and environment in SMAC

### ISSUE THREAD

**Issue by waterhorse1** [marlbenchmark/on-policy#40]
Hi authors,

Really appreciate this nice codebase for MAPPO. I have one issue that I find out the environment used in MAPPO is somehow different with the environment in SMAC. For example, you can compare how this environment and starcraft in SMAC implement the global_state function: 

https://github.com/oxwhirl/smac/blob/a54ebb937e44dc9c703d96064f423069532c7b66/smac/env/starcraft2/starcraft2.py#L1135

https://github.com/marlbenchmark/on-policy/blob/98c40d3112d63d21d792b638ca6e42786758c648/onpolicy/envs/starcraft2/StarCraft2_Env.py#L1152

The get_state function in SMAC is the real global state while the get_state function in your starcraft is still an agent-dependent state. I am wondering why these two environments are different.

**Comment by zoeyuchao** [comment]
i guess u did not read our paper，we explain this in the state represention ***@***.***: https://nicsefc.ee.tsinghua.edu.cn/people/zoeyuchao/ Address: Shuangqing 5302, Department of Electronic Engineering, Tsinghua University, Beijing 100084, P.R.China------------------ Original ------------------From: Xidong Feng  ***@***.***>Date: Thu,Apr 28,2022 6:12 AMTo: marlbenchmark/on-policy ***@***.***>Cc: Subscribed ***@***.***>Subject: Re: [marlbenchmark/on-policy] Differences between the starcraftenvironment and environment in SMAC (Issue #40)
Hi authors,
Really appreciate this nice codebase for MAPPO. I have one issue that I find out the environment used in MAPPO is somehow different with the environment in SMAC. For example, you can compare how this environment and starcraft in SMAC implement the global_state function:
https://github.com/oxwhirl/smac/blob/a54ebb937e44dc9c703d96064f423069532c7b66/smac/env/starcraft2/starcraft2.py#L1135
https://github.com/marlbenchmark/on-policy/blob/98c40d3112d63d21d792b638ca6e42786758c648/onpolicy/envs/starcraft2/StarCraft2_Env.py#L1152
The get_state function in SMAC is the real global state while the get_state function in your starcraft is still an agent-dependent state. I am wondering why these two environments are different.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/marlbenchmark/on-policy/issues/40",
"url": "https://github.com/marlbenchmark/on-policy/issues/40",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by waterhorse1** [comment]
thx for your answer!
